#!/bin/bash
buildjs=build/build.js
version=$(cat version)

build() {
  mkdir -p build
  manifest
  search_dir=src
  for entry in "$search_dir"/*; do
    echo "//file $entry" >>$buildjs
    while IFS= read -r line; do
      echo "$line" >>$buildjs
    done <"$entry"
  done
  echo "successful build"
}

manifest() {
  printf "MODULE(" >$buildjs
  cat manifest.json >>$buildjs
  echo ");" >>$buildjs
}

release() {
  mkdir -p release
  build
}

if [ "$1" = "build" ]; then
  build
  cp $buildjs ~/S.A.U.W./Modules/test.js
elif [ "$1" = "release" ]; then
  release
  cp $buildjs "release/$version.js"
fi
